In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv", sep = ",")

In [3]:
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [7]:
#thong tin kieu du lieu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [6]:
#so cot so dong
df.shape

(299, 13)

In [9]:
#tinh max mean trung vi
df.describe(include = "all")

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

In [11]:
df.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [12]:
#chon dac trung
ft = ["age", "anaemia", "creatinine_phosphokinase", "diabetes",
       "ejection_fraction", "high_blood_pressure", "platelets",
       "serum_creatinine", "serum_sodium", "sex", "smoking", "time"]

In [15]:
#chia du lieu thanh x va y
X = df[ft]
Y = df["DEATH_EVENT"]

In [14]:
X.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  
0        0     4  
1        0     6  
2        1     7  
3        0     7  
4        0     8

In [16]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: DEATH_EVENT, dtype: int64

In [18]:
#chia du lieu thanh tep train va tep test
from sklearn.model_selection import train_test_split
X_train, X_valid, Y_train, Y_valid = train_test_split(X,Y, train_size = 0.8, test_size = 0.2, random_state = 0)

In [20]:
X_train.shape

(239, 12)

In [22]:
X_valid.shape

(60, 12)

In [23]:
X.shape

(299, 12)

In [24]:
Y_train.shape

(239,)

In [25]:
Y_valid.shape

(60,)

In [26]:
Y.shape

(299,)

In [29]:
#huan luyen mo hinh
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state = 1)

In [31]:
#cho du lieu vao mo hinh
dt_model.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=1)

In [32]:
Y_preds = dt_model.predict(X_valid.head())

In [33]:
Y_preds

array([0, 0, 0, 0, 0], dtype=int64)

In [34]:
pd.DataFrame({'Y':Y_valid.head(), 'Y_preds' : Y_preds})

Y  Y_preds
206  0        0
188  0        0
12   1        0
219  0        0
237  0        0

In [35]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
rf_model=RandomForestClassifier(random_state=1)
rf_model.fit(X_train, Y_train)

RandomForestClassifier(random_state=1)

In [36]:
rf_val_perds = rf_model.predict(X_valid)

In [37]:
rf_val_perds[:5]

array([0, 0, 1, 0, 0], dtype=int64)

In [40]:
#dua mot du lieu moi de du doan
rf_model.predict([[70,0, 400,0,50,1,300000,1.0,150,0,1,30]])

D:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [38]:
X_valid.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
206  40.000        1                       101         0                 40   
188  60.667        1                       151         1                 40   
12   45.000        1                       981         0                 30   
219  55.000        0                       582         1                 35   
237  70.000        0                       232         0                 30   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
206                    0   226000.0               0.8           141    0   
188                    1   201000.0               1.0           136    0   
12                     0   136000.0               1.1           137    1   
219                    1   371000.0               0.7           140    0   
237                    0   173000.0               1.2           132    1   

     smoking  time  
206        0   187  
188        0   172  
12         0    11  
219        0   197  
237        0   210